### ISSUE TITLE
How to access the model in a route

### ISSUE THREAD

**Issue by sn0rcha** [mhuggins/sequelize-middleware#1]
Hey There,

Thanks for the module. I'm using it as you explained to import all my model files. I was wondering how I  actually access the model inside a route? - Sorry I'm new to express :)

Cheers,
Ben

**Comment by mhuggins** [comment]
Here's an example of how I'm loading a user's profile in a route:

``` js
exports.show = function (req, res, next) {
  req.models.User.find({ where: { username: req.params.id } })
      .error(next)
      .success(function (user) {
        if (user) {
          res.render('users/show', { user: user });
        } else {
          res.render('errors/404');
        }
      });
};
```

**Comment by sn0rcha** [comment]
Many thanks
